name: 'walmart_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'walmart_dbt_project'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  walmart_dbt_project:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table

snapshots:
  walmart_dbt_project:
    +target_schema: MARTS
    +strategy: check